"""
Claude-based rule classifier for DancePlatform.
Applies style/music/difficulty based on hardcoded dance knowledge.
Skips (keeps existing) anything that can't be confidently classified.
"""
import json, time, re
import urllib.request, urllib.error

API_BASE = "https://dance-api.takelord.com/api"

# ── Style IDs ──────────────────────────────────────────────────────────────
LATIN=1; BALLROOM=2; STREET=3; BALLET=4; FOLK=5; SWING=6
CONTEMPORARY=7; WAACKING=8; TEKTONIK=9; HIPHOP=10; HOUSE=11
BREAKDANCE=12; AFROBEATS=13; DANCEHALL=14; KRUMP=15; VOGUE=16
BHANGRA=17; FLAMENCO=18; TAP=19; JAZZ=20; KPOP=21

# ── Music IDs ──────────────────────────────────────────────────────────────
SALSA=1; CLASSICAL=2; MHIPHOP=3; MJAZZ=4; TANGO=5; EDM=6
BLUES=7; REGGAETON=8; CUMBIA=9; MFLAMENCO=10; MAFRO=11
MDANCEHALL=12; BHANGRA_M=13; JPOP=14

# ── helpers ────────────────────────────────────────────────────────────────
def api(method, path, body=None, token=None):
    url = API_BASE + path
    data = json.dumps(body).encode() if body else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Content-Type", "application/json")
    if token: req.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.loads(r.read()), r.status
    except urllib.error.HTTPError as e:
        return None, e.code

def login():
    body, _ = api("POST", "/auth/login", {"username":"justas","password":"Dance@Admin2026"})
    return body["token"]

# ── EXACT lookup: name.lower() → ([style_ids], [music_ids], difficulty) ───
EXACT = {
    # ── Hip-hop golden era ──────────────────────────────────────────────
    "running man":([HIPHOP],[MHIPHOP],"Beginner"),
    "cabbage patch":([HIPHOP],[MHIPHOP],"Beginner"),
    "roger rabbit":([HIPHOP],[MHIPHOP],"Beginner"),
    "mc rock":([HIPHOP],[MHIPHOP],"Beginner"),
    "patty duke":([HIPHOP],[MHIPHOP],"Beginner"),
    "smurf":([HIPHOP],[MHIPHOP],"Beginner"),
    "the prep":([HIPHOP],[MHIPHOP],"Beginner"),
    "stomp":([HIPHOP],[MHIPHOP],"Beginner"),
    "snake":([HIPHOP],[MHIPHOP],"Beginner"),
    "reebok":([HIPHOP],[MHIPHOP],"Beginner"),
    "fila":([HIPHOP],[MHIPHOP],"Beginner"),
    "tlc":([HIPHOP],[MHIPHOP],"Beginner"),
    "rooftop":([HIPHOP],[MHIPHOP],"Beginner"),
    "steve martin":([HIPHOP],[MHIPHOP],"Beginner"),
    "butterfly":([HIPHOP],[MHIPHOP],"Beginner"),
    "bankhead bounce":([HIPHOP],[MHIPHOP],"Beginner"),
    "atl":([HIPHOP],[MHIPHOP],"Beginner"),
    "atl stomp":([HIPHOP],[MHIPHOP],"Beginner"),
    "outlaw":([HIPHOP],[MHIPHOP],"Beginner"),
    "guess":([HIPHOP],[MHIPHOP],"Beginner"),
    "skate":([HIPHOP],[MHIPHOP],"Beginner"),
    "monastery/chicken head":([HIPHOP],[MHIPHOP],"Beginner"),
    "monestary":([HIPHOP],[MHIPHOP],"Beginner"),
    "kid at play":([HIPHOP],[MHIPHOP],"Beginner"),
    "party machine":([HIPHOP],[MHIPHOP],"Beginner"),
    "spongebob":([HIPHOP],[MHIPHOP],"Beginner"),
    "sponge bob":([HIPHOP],[MHIPHOP],"Beginner"),
    "bernie":([HIPHOP],[MHIPHOP],"Beginner"),
    "bk bounce":([HIPHOP],[MHIPHOP],"Beginner"),
    "brooklyne":([HIPHOP],[MHIPHOP],"Beginner"),
    "aunt viv":([HIPHOP],[MHIPHOP],"Beginner"),
    "james brown":([HIPHOP],[MHIPHOP],"Beginner"),
    "shamrock":([HIPHOP],[MHIPHOP],"Beginner"),
    "wreckin shop":([HIPHOP],[MHIPHOP],"Beginner"),
    "camel walk":([HIPHOP],[MHIPHOP],"Beginner"),
    "janet jackson":([HIPHOP],[MHIPHOP],"Beginner"),
    "alf":([HIPHOP],[MHIPHOP],"Beginner"),
    "happy feet":([HIPHOP],[MHIPHOP],"Beginner"),
    "di da":([HIPHOP],[MHIPHOP],"Beginner"),
    "cameo":([HIPHOP],[MHIPHOP],"Beginner"),
    "reject":([HIPHOP],[MHIPHOP],"Beginner"),
    "c walk":([STREET],[MHIPHOP],"Beginner"),
    "aunt jackie":([HIPHOP],[MHIPHOP],"Beginner"),
    "walk out":([HIPHOP],[MHIPHOP],"Beginner"),
    "walk it out":([HIPHOP],[MHIPHOP],"Beginner"),
    "gucci":([HIPHOP],[MHIPHOP],"Beginner"),
    "popcorn":([HIPHOP],[MHIPHOP],"Beginner"),
    "fly girls":([HIPHOP],[MHIPHOP],"Beginner"),
    "upstairs downstairs":([HIPHOP],[MHIPHOP],"Beginner"),
    "bobby brown":([HIPHOP],[MHIPHOP],"Beginner"),
    "biz markie":([HIPHOP],[MHIPHOP],"Beginner"),
    "kriss kross":([HIPHOP],[MHIPHOP],"Beginner"),
    "robocop":([HIPHOP],[MHIPHOP],"Beginner"),
    "dougie":([HIPHOP],[MHIPHOP],"Beginner"),
    "wop":([HIPHOP],[MHIPHOP],"Beginner"),
    "bart simpson":([HIPHOP],[MHIPHOP],"Beginner"),
    "wu-tang":([HIPHOP],[MHIPHOP],"Beginner"),
    "wutang":([HIPHOP],[MHIPHOP],"Beginner"),
    "funky watergate":([HIPHOP],[MHIPHOP],"Beginner"),
    "cat daddy":([HIPHOP],[MHIPHOP],"Beginner"),
    "carlton":([HIPHOP],[MHIPHOP],"Beginner"),
    "harlem shake":([HIPHOP],[MHIPHOP],"Beginner"),
    "millie rock":([HIPHOP],[MHIPHOP],"Beginner"),
    "milly rock":([HIPHOP],[MHIPHOP],"Beginner"),
    "raise the roof":([HIPHOP],[MHIPHOP],"Beginner"),
    "moonwalk":([STREET],[MHIPHOP],"Intermediate"),
    "the moonwalk":([STREET],[MHIPHOP],"Intermediate"),
    "the running man":([HIPHOP],[MHIPHOP],"Beginner"),
    "the cabbage patch":([HIPHOP],[MHIPHOP],"Beginner"),
    "the stanky leg":([HIPHOP],[MHIPHOP],"Beginner"),
    "the wop":([HIPHOP],[MHIPHOP],"Beginner"),
    "the floss":([HIPHOP],[MHIPHOP],"Beginner"),
    "the dab":([HIPHOP],[MHIPHOP],"Beginner"),
    "the dougie":([HIPHOP],[MHIPHOP],"Beginner"),
    "the jerk":([STREET],[MHIPHOP],"Beginner"),
    "stanky leg":([HIPHOP],[MHIPHOP],"Beginner"),
    "loose legs":([HIPHOP],[MHIPHOP],"Beginner"),
    "jerk":([STREET],[MHIPHOP],"Beginner"),
    "drop dance":([HIPHOP],[MHIPHOP],"Beginner"),
    "drop it low":([HIPHOP],[MHIPHOP],"Beginner"),
    "dip it low":([HIPHOP],[MHIPHOP],"Beginner"),
    "milkshake":([HIPHOP],[MHIPHOP],"Beginner"),
    "juju step":([AFROBEATS],[MAFRO],"Beginner"),
    "pop and lock":([HIPHOP],[MHIPHOP],"Intermediate"),
    "robot":([HIPHOP],[MHIPHOP],"Beginner"),
    "the robot":([HIPHOP],[MHIPHOP],"Beginner"),
    "arm wave":([HIPHOP],[MHIPHOP],"Intermediate"),
    "the arm wave":([HIPHOP],[MHIPHOP],"Intermediate"),
    "popping":([HIPHOP],[MHIPHOP],"Intermediate"),
    "locking":([HIPHOP],[MHIPHOP],"Intermediate"),
    "finger tutting":([HIPHOP],[MHIPHOP],"Intermediate"),
    "chest pop":([HIPHOP],[MHIPHOP],"Beginner"),
    "the chest pop":([HIPHOP],[MHIPHOP],"Beginner"),
    "hip swivel":([HIPHOP],[MHIPHOP],"Beginner"),
    "shimmy":([HIPHOP],[MHIPHOP],"Beginner"),
    "glide":([HIPHOP],[MHIPHOP],"Intermediate"),
    "robot move":([HIPHOP],[MHIPHOP],"Beginner"),
    "robo hop":([HIPHOP],[MHIPHOP],"Beginner"),
    "pogo stick":([HIPHOP],[MHIPHOP],"Beginner"),
    "bounce":([HIPHOP],[MHIPHOP],"Beginner"),
    "sway":([HIPHOP],[MHIPHOP],"Beginner"),
    "basic running man":([HIPHOP],[MHIPHOP],"Beginner"),
    "running man variation":([HIPHOP],[MHIPHOP],"Beginner"),
    "running man reverse":([HIPHOP],[MHIPHOP],"Beginner"),
    "running man moonwalk":([HIPHOP],[MHIPHOP],"Intermediate"),
    "running man & heel twist":([HIPHOP],[MHIPHOP],"Beginner"),
    "running man & t-step":([HIPHOP],[MHIPHOP],"Beginner"),
    "running man & kick":([HIPHOP],[MHIPHOP],"Beginner"),
    "running man heel":([HIPHOP],[MHIPHOP],"Beginner"),
    "running man & stepback":([HIPHOP],[MHIPHOP],"Beginner"),
    "diagonal running man stepback":([HIPHOP],[MHIPHOP],"Beginner"),
    "diagonal running man & flick":([HIPHOP],[MHIPHOP],"Beginner"),
    "t-step reverse":([HIPHOP],[MHIPHOP],"Beginner"),
    "t-step heel toe":([HIPHOP],[MHIPHOP],"Beginner"),
    "t-step angle":([HIPHOP],[MHIPHOP],"Beginner"),
    "spongebob shuffle reverse":([HIPHOP],[MHIPHOP],"Beginner"),
    "spongebob shuffle kick out":([HIPHOP],[MHIPHOP],"Beginner"),
    "spongebob shuffle variation":([HIPHOP],[MHIPHOP],"Beginner"),
    "spongebob shuffle hop":([HIPHOP],[MHIPHOP],"Beginner"),
    "charleston variation":([HIPHOP],[MHIPHOP],"Beginner"),
    "charleston & cowtail":([HIPHOP],[MHIPHOP],"Beginner"),
    "charleston & running man":([HIPHOP],[MHIPHOP],"Beginner"),
    "criss cross variation":([HIPHOP],[MHIPHOP],"Beginner"),
    "criss cross hop & tap":([HIPHOP],[MHIPHOP],"Beginner"),
    "v-step back":([HIPHOP],[MHIPHOP],"Beginner"),
    "happy feet combo":([HIPHOP],[MHIPHOP],"Beginner"),
    "heel toe hop":([HIPHOP],[MHIPHOP],"Beginner"),
    "heel toe & toe twist":([HIPHOP],[MHIPHOP],"Beginner"),
    "heel toe snake":([HIPHOP],[MHIPHOP],"Beginner"),
    "heel toe travel & flick":([HIPHOP],[MHIPHOP],"Beginner"),
    "indian step":([HIPHOP],[MHIPHOP],"Beginner"),
    "cross step":([HIPHOP],[MHIPHOP],"Beginner"),
    "pocket drop":([HIPHOP],[MHIPHOP],"Beginner"),
    "rock steady":([HIPHOP],[MHIPHOP],"Beginner"),
    "swag walk":([HIPHOP],[MHIPHOP],"Beginner"),
    "bicycle":([HIPHOP],[MHIPHOP],"Beginner"),
    "froggy":([HIPHOP],[MHIPHOP],"Beginner"),
    "swoop and dip":([HIPHOP],[MHIPHOP],"Beginner"),
    "head tilt":([HIPHOP],[MHIPHOP],"Beginner"),
    "dance floor bump":([HIPHOP],[MHIPHOP],"Beginner"),
    "hip circle":([HIPHOP],[MHIPHOP],"Beginner"),
    "chaser step":([HIPHOP],[MHIPHOP],"Beginner"),
    "l-step":([HIPHOP],[MHIPHOP],"Beginner"),
    "walking breakdown":([HIPHOP],[MHIPHOP],"Beginner"),
    "bust it baby":([HIPHOP],[MHIPHOP],"Beginner"),
    "sassy walk":([HIPHOP],[MHIPHOP],"Beginner"),
    "shake your hips":([HIPHOP],[MHIPHOP],"Beginner"),
    "stomp the floor":([HIPHOP],[MHIPHOP],"Beginner"),
    "honey dipper":([HIPHOP],[MHIPHOP],"Beginner"),
    "the sprinkler":([HIPHOP],[MHIPHOP],"Beginner"),
    "tootsie roll":([HIPHOP],[MHIPHOP],"Beginner"),
    "swim buggy":([HIPHOP],[MHIPHOP],"Beginner"),
    "robot flair floss":([HIPHOP],[MHIPHOP],"Beginner"),
    "the chicken":([HIPHOP],[MHIPHOP],"Beginner"),
    "the mashed potato":([HIPHOP],[MHIPHOP],"Beginner"),
    "mashed potato":([HIPHOP],[MHIPHOP],"Beginner"),
    "the twist":([HIPHOP],[MHIPHOP],"Beginner"),
    "the shimmy":([JAZZ],[MJAZZ],"Beginner"),
    "the bump":([HIPHOP],[MHIPHOP],"Beginner"),
    "the swim":([HIPHOP],[MHIPHOP],"Beginner"),
    "the monkey":([HIPHOP],[MHIPHOP],"Beginner"),
    "the pony":([HIPHOP],[MHIPHOP],"Beginner"),
    "the funky chicken":([HIPHOP],[MHIPHOP],"Beginner"),
    "the watusi":([FOLK],[MHIPHOP],"Beginner"),
    "the ska":([FOLK],[MJAZZ],"Beginner"),
    "the rocksteady":([DANCEHALL],[MDANCEHALL],"Beginner"),
    "the hand jive":([JAZZ],[MJAZZ],"Beginner"),
    "the stroll":([SWING],[MJAZZ],"Beginner"),
    "the electric slide":([FOLK],[MHIPHOP],"Beginner"),
    "the cupid shuffle":([FOLK],[MHIPHOP],"Beginner"),
    "the cha cha slide":([LATIN],[SALSA],"Beginner"),
    "the waltz":([BALLROOM],[CLASSICAL],"Intermediate"),
    "the tango":([BALLROOM],[TANGO],"Intermediate"),
    "the head banger":([HIPHOP],[MHIPHOP],"Beginner"),
    "the hustle":([LATIN],[SALSA],"Intermediate"),
    "the chug":([SWING],[MJAZZ],"Beginner"),
    "cupid shuffle":([FOLK],[MHIPHOP],"Beginner"),
    "boot scootin' boogie":([FOLK],[MHIPHOP],"Beginner"),
    "funky chicken":([HIPHOP],[MHIPHOP],"Beginner"),
    "electric slide":([FOLK],[MHIPHOP],"Beginner"),
    "wobble":([FOLK],[MHIPHOP],"Beginner"),
    "the wobble":([FOLK],[MHIPHOP],"Beginner"),
    "cha cha slide":([LATIN],[SALSA],"Beginner"),
    "milly rock":([HIPHOP],[MHIPHOP],"Beginner"),
    "the milly rock":([HIPHOP],[MHIPHOP],"Beginner"),
    "side to side":([HIPHOP],[MHIPHOP],"Beginner"),
    "pony":([HIPHOP],[MHIPHOP],"Beginner"),
    "the pony":([HIPHOP],[MHIPHOP],"Beginner"),
    # ── Breakdance ─────────────────────────────────────────────────────────
    "baby freeze":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "chair freeze":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "headstand":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "handstand":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "turtle":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "turtle switch":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "pin drop":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "coffee grinder":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "six step":([BREAKDANCE],[MHIPHOP],"Beginner"),
    "6-step":([BREAKDANCE],[MHIPHOP],"Beginner"),
    "6 step":([BREAKDANCE],[MHIPHOP],"Beginner"),
    "6-step":([BREAKDANCE],[MHIPHOP],"Beginner"),
    "6step":([BREAKDANCE],[MHIPHOP],"Beginner"),
    "frog pose":([BREAKDANCE],[MHIPHOP],"Beginner"),
    "frog pose to turtle":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "knee slide up":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "toe slide":([BREAKDANCE],[MHIPHOP],"Beginner"),
    "donkey":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "kickup":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "elbow cartwheel":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "v kick":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "roll back up":([BREAKDANCE],[MHIPHOP],"Beginner"),
    "knee switches":([BREAKDANCE],[MHIPHOP],"Beginner"),
    "leg thread":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "leg thead":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "shoulder roll":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "coin":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "swipe":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "flare":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "windmill":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "headspin":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "airchair":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "airfreeze":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "airporkchop":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "barrel roll":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "backflip":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "birds nest":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "double flare":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "drop top rock":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "helicopter":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "hurricane":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "mule kick":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "scrape":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "spin top":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "spring forward":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "squat thug":([BREAKDANCE],[MHIPHOP],"Beginner"),
    "toprocks":([BREAKDANCE],[MHIPHOP],"Beginner"),
    "footworks":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "freezes":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "powermoves":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "power move":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "kip up":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "flip":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "banger":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "bubble":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "chandelier":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "collapsing flip":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "elephant walk":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "freeze frame":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "gazelle":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "ghost step":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "hook turn":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "inversion flip-over":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "z-sit pike throw":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "chug knee spin":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "crazy legs":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "walkover":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "cartwheel":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "blade":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "top rock":([BREAKDANCE],[MHIPHOP],"Beginner"),
    "toprock":([BREAKDANCE],[MHIPHOP],"Beginner"),
    "side rock":([BREAKDANCE],[MHIPHOP],"Beginner"),
    "knee pose":([BREAKDANCE],[MHIPHOP],"Beginner"),
    "4 count freeze":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "6-step":([BREAKDANCE],[MHIPHOP],"Beginner"),
    "needle slide through":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "windmill into roll":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "front shoulder roll variation":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "barrel jump variation":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "waterfall":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "shoulder roll variation":([BREAKDANCE],[MHIPHOP],"Intermediate"),
    "rolling cartwheel":([BREAKDANCE],[MHIPHOP],"Advanced"),
    "handstand to the floor":([BREAKDANCE],[MHIPHOP],"Advanced"),
    # ── Ballet / Classical ─────────────────────────────────────────────────
    "plié":([BALLET],[CLASSICAL],"Beginner"),
    "plie":([BALLET],[CLASSICAL],"Beginner"),
    "pliés":([BALLET],[CLASSICAL],"Beginner"),
    "plies":([BALLET],[CLASSICAL],"Beginner"),
    "tendu":([BALLET],[CLASSICAL],"Beginner"),
    "dégagé":([BALLET],[CLASSICAL],"Beginner"),
    "degagé":([BALLET],[CLASSICAL],"Beginner"),
    "dégage":([BALLET],[CLASSICAL],"Beginner"),
    "degage":([BALLET],[CLASSICAL],"Beginner"),
    "arabesque":([BALLET],[CLASSICAL],"Intermediate"),
    "arabesque penchée":([BALLET],[CLASSICAL],"Advanced"),
    "arabesque penchee":([BALLET],[CLASSICAL],"Advanced"),
    "pirouette":([BALLET],[CLASSICAL],"Intermediate"),
    "fouetté":([BALLET],[CLASSICAL],"Advanced"),
    "fouette":([BALLET],[CLASSICAL],"Advanced"),
    "fouetté sauté":([BALLET],[CLASSICAL],"Advanced"),
    "fouette saute":([BALLET],[CLASSICAL],"Advanced"),
    "fouette turns":([BALLET],[CLASSICAL],"Advanced"),
    "fouette turns":([BALLET],[CLASSICAL],"Advanced"),
    "jeté":([BALLET],[CLASSICAL],"Intermediate"),
    "jete":([BALLET],[CLASSICAL],"Intermediate"),
    "grand jeté":([BALLET],[CLASSICAL],"Advanced"),
    "grande jeté":([BALLET],[CLASSICAL],"Advanced"),
    "échappé":([BALLET],[CLASSICAL],"Intermediate"),
    "echappe":([BALLET],[CLASSICAL],"Intermediate"),
    "assemblé":([BALLET],[CLASSICAL],"Intermediate"),
    "assemble":([BALLET],[CLASSICAL],"Intermediate"),
    "glissade":([BALLET],[CLASSICAL],"Intermediate"),
    "soutenu":([BALLET],[CLASSICAL],"Intermediate"),
    "pas de chat":([BALLET],[CLASSICAL],"Intermediate"),
    "tour en l'air":([BALLET],[CLASSICAL],"Advanced"),
    "couru":([BALLET],[CLASSICAL],"Intermediate"),
    "relevé":([BALLET],[CLASSICAL],"Beginner"),
    "releve":([BALLET],[CLASSICAL],"Beginner"),
    "relevés":([BALLET],[CLASSICAL],"Beginner"),
    "relever":([BALLET],[CLASSICAL],"Beginner"),
    "battement":([BALLET],[CLASSICAL],"Intermediate"),
    "grand battement":([BALLET],[CLASSICAL],"Intermediate"),
    "en dedans":([BALLET],[CLASSICAL],"Intermediate"),
    "en dehors":([BALLET],[CLASSICAL],"Intermediate"),
    "développé":([BALLET],[CLASSICAL],"Advanced"),
    "developpe":([BALLET],[CLASSICAL],"Advanced"),
    "developpé":([BALLET],[CLASSICAL],"Advanced"),
    "en pointe":([BALLET],[CLASSICAL],"Advanced"),
    "écarté":([BALLET],[CLASSICAL],"Intermediate"),
    "ecarte":([BALLET],[CLASSICAL],"Intermediate"),
    "rond de jambe":([BALLET],[CLASSICAL],"Intermediate"),
    "ronde de jambe":([BALLET],[CLASSICAL],"Intermediate"),
    "ronds de jambe":([BALLET],[CLASSICAL],"Intermediate"),
    "petite allegro":([BALLET],[CLASSICAL],"Intermediate"),
    "pirouette en pointe":([BALLET],[CLASSICAL],"Advanced"),
    "bourrée":([BALLET],[CLASSICAL],"Intermediate"),
    "bourree":([BALLET],[CLASSICAL],"Intermediate"),
    "attitude":([BALLET],[CLASSICAL],"Intermediate"),
    "cabriole":([BALLET],[CLASSICAL],"Advanced"),
    "coupe":([BALLET],[CLASSICAL],"Intermediate"),
    "coupé":([BALLET],[CLASSICAL],"Intermediate"),
    "double tour en l'air":([BALLET],[CLASSICAL],"Advanced"),
    "double cabriole":([BALLET],[CLASSICAL],"Advanced"),
    "revoltade":([BALLET],[CLASSICAL],"Advanced"),
    "barrel turns":([BALLET],[CLASSICAL],"Advanced"),
    "double assemblé en tournant":([BALLET],[CLASSICAL],"Advanced"),
    "double saut de basque":([BALLET],[CLASSICAL],"Advanced"),
    "à la seconde turns":([BALLET],[CLASSICAL],"Advanced"),
    "consecutive entrechat six":([BALLET],[CLASSICAL],"Advanced"),
    "coupé jeté en manège":([BALLET],[CLASSICAL],"Advanced"),
    "sauté":([BALLET],[CLASSICAL],"Intermediate"),
    "saute":([BALLET],[CLASSICAL],"Intermediate"),
    "fondu":([BALLET],[CLASSICAL],"Intermediate"),
    "frappé":([BALLET],[CLASSICAL],"Intermediate"),
    "frappe":([BALLET],[CLASSICAL],"Intermediate"),
    "adagio":([BALLET],[CLASSICAL],"Advanced"),
    "adage":([BALLET],[CLASSICAL],"Advanced"),
    "pas de bourré":([BALLET],[CLASSICAL],"Intermediate"),
    "pas de bourree":([BALLET],[CLASSICAL],"Intermediate"),
    "pas de bourré'e":([BALLET],[CLASSICAL],"Intermediate"),
    "pas de bourrée":([BALLET],[CLASSICAL],"Intermediate"),
    "pas de bourrée":([BALLET],[CLASSICAL],"Intermediate"),
    "pas de bourre'e":([BALLET],[CLASSICAL],"Intermediate"),
    "sous sous":([BALLET],[CLASSICAL],"Intermediate"),
    "changement":([BALLET],[CLASSICAL],"Intermediate"),
    "tournant":([BALLET],[CLASSICAL],"Intermediate"),
    "élevé":([BALLET],[CLASSICAL],"Beginner"),
    "eleve":([BALLET],[CLASSICAL],"Beginner"),
    "soutenu en l'air":([BALLET],[CLASSICAL],"Advanced"),
    "jeté en l'air":([BALLET],[CLASSICAL],"Advanced"),
    "jeté cloche":([BALLET],[CLASSICAL],"Advanced"),
    "contrapposto":([BALLET],[CLASSICAL],"Beginner"),
    "plié à la seconde":([BALLET],[CLASSICAL],"Intermediate"),
    "détendu":([BALLET],[CLASSICAL],"Beginner"),
    "detendu":([BALLET],[CLASSICAL],"Beginner"),
    "lungeline":([BALLET],[CLASSICAL],"Intermediate"),
    "vestige":([BALLET],[CLASSICAL],"Intermediate"),
    "1st position":([BALLET],[CLASSICAL],"Beginner"),
    "2nd position":([BALLET],[CLASSICAL],"Beginner"),
    "3rd position":([BALLET],[CLASSICAL],"Beginner"),
    "4th position":([BALLET],[CLASSICAL],"Beginner"),
    "5th position":([BALLET],[CLASSICAL],"Beginner"),
    "6th position":([BALLET],[CLASSICAL],"Beginner"),
    "port de bras":([BALLET],[CLASSICAL],"Intermediate"),
    "rassembler":([BALLET],[CLASSICAL],"Intermediate"),
    "désarmé":([BALLET],[CLASSICAL],"Intermediate"),
    "alembra":([BALLET],[CLASSICAL],"Intermediate"),
    "tournant en avant":([BALLET],[CLASSICAL],"Intermediate"),
    "tournant en arrière":([BALLET],[CLASSICAL],"Intermediate"),
    "saute-à-gauche":([BALLET],[CLASSICAL],"Intermediate"),
    "saute-à-droite":([BALLET],[CLASSICAL],"Intermediate"),
    "tour jeté":([BALLET],[CLASSICAL],"Advanced"),
    "ronds de jambe en l'air":([BALLET],[CLASSICAL],"Intermediate"),
    "en avant et en arrière":([BALLET],[CLASSICAL],"Beginner"),
    "dégagé 1st":([BALLET],[CLASSICAL],"Beginner"),
    "degagé 1st":([BALLET],[CLASSICAL],"Beginner"),
    "dégagé 5th":([BALLET],[CLASSICAL],"Beginner"),
    "degagé 5th":([BALLET],[CLASSICAL],"Beginner"),
    "dégage 1st":([BALLET],[CLASSICAL],"Beginner"),
    "dégage 5th":([BALLET],[CLASSICAL],"Beginner"),
    "degagé 1st":([BALLET],[CLASSICAL],"Beginner"),
    "degagé 5th":([BALLET],[CLASSICAL],"Beginner"),
    "dégage 1st":([BALLET],[CLASSICAL],"Beginner"),
    "tendu 1st":([BALLET],[CLASSICAL],"Beginner"),
    "tendu 5th":([BALLET],[CLASSICAL],"Beginner"),
    "pas de cheval":([BALLET],[CLASSICAL],"Intermediate"),
    "coupé & tendu":([BALLET],[CLASSICAL],"Beginner"),
    "plié & straight leg relevé":([BALLET],[CLASSICAL],"Beginner"),
    "tendu & shaping feet":([BALLET],[CLASSICAL],"Beginner"),
    "relevé on 1 leg":([BALLET],[CLASSICAL],"Intermediate"),
    "sous sous":([BALLET],[CLASSICAL],"Intermediate"),
    "balance & stretch":([BALLET],[CLASSICAL],"Beginner"),
    "turnout exercise":([BALLET],[CLASSICAL],"Beginner"),
    "spiral":([CONTEMPORARY],[CLASSICAL],"Intermediate"),
    "dégagé fouetté":([BALLET],[CLASSICAL],"Advanced"),
    "saute-à-gauche battu":([BALLET],[CLASSICAL],"Advanced"),
    "fouetté à terre":([BALLET],[CLASSICAL],"Advanced"),
    "ronds de jambe":([BALLET],[CLASSICAL],"Intermediate"),
    "sauté":([BALLET],[CLASSICAL],"Intermediate"),
    "saute-à-gauche":([BALLET],[CLASSICAL],"Intermediate"),
    "saute-à-droite":([BALLET],[CLASSICAL],"Intermediate"),
    "jeté en l'air":([BALLET],[CLASSICAL],"Advanced"),
    "tournant jeté":([BALLET],[CLASSICAL],"Advanced"),
    "arabesque en l'air":([BALLET],[CLASSICAL],"Advanced"),
    "arabesque a terre":([BALLET],[CLASSICAL],"Intermediate"),
    "attitude arabesque":([BALLET],[CLASSICAL],"Advanced"),
    "pirouette en dedans":([BALLET],[CLASSICAL],"Intermediate"),
    "st arabesque":([BALLET],[CLASSICAL],"Intermediate"),
    "nd arabesque":([BALLET],[CLASSICAL],"Intermediate"),
    "rd arabesque":([BALLET],[CLASSICAL],"Advanced"),
    "battement fondu":([BALLET],[CLASSICAL],"Intermediate"),
    "battement frappé":([BALLET],[CLASSICAL],"Intermediate"),
    "battement cloche":([BALLET],[CLASSICAL],"Intermediate"),
    "battement frappe":([BALLET],[CLASSICAL],"Intermediate"),
    "adage":([BALLET],[CLASSICAL],"Advanced"),
    "port de bras":([BALLET],[CLASSICAL],"Intermediate"),
    "slow jete":([BALLET],[CLASSICAL],"Intermediate"),
    "pique":([BALLET],[CLASSICAL],"Intermediate"),
    "fond - intro.exercise":([BALLET],[CLASSICAL],"Intermediate"),
    "développé exercise":([BALLET],[CLASSICAL],"Advanced"),
    "développé":([BALLET],[CLASSICAL],"Advanced"),
    "developpé":([BALLET],[CLASSICAL],"Advanced"),
    # ── Latin ──────────────────────────────────────────────────────────────
    "salsa":([LATIN],[SALSA],"Intermediate"),
    "bachata":([LATIN],[REGGAETON],"Beginner"),
    "merengue":([LATIN],[SALSA],"Beginner"),
    "cha-cha":([LATIN],[SALSA],"Intermediate"),
    "cha cha":([LATIN],[SALSA],"Intermediate"),
    "samba":([LATIN],[SALSA],"Intermediate"),
    "mambo":([LATIN],[SALSA],"Intermediate"),
    "rumba":([LATIN],[SALSA],"Intermediate"),
    "american rumba":([LATIN],[SALSA],"Intermediate"),
    "international rumba":([LATIN],[SALSA],"Intermediate"),
    "american cha cha":([LATIN],[SALSA],"Intermediate"),
    "international cha cha":([LATIN],[SALSA],"Intermediate"),
    "paso doble":([LATIN],[SALSA],"Advanced"),
    "cumbia":([LATIN],[CUMBIA],"Beginner"),
    "bolero":([LATIN],[SALSA],"Intermediate"),
    "cuban motion":([LATIN],[SALSA],"Intermediate"),
    "cross-body lead":([LATIN],[SALSA],"Intermediate"),
    "rueda de casino":([LATIN],[SALSA],"Advanced"),
    "bachata step":([LATIN],[REGGAETON],"Beginner"),
    "salsa limpio":([LATIN],[SALSA],"Intermediate"),
    "perico limpio":([LATIN],[SALSA],"Intermediate"),
    "reggaeton bounce":([LATIN],[REGGAETON],"Beginner"),
    "guateque":([LATIN],[SALSA],"Beginner"),
    "meneo":([LATIN],[SALSA],"Beginner"),
    "el perico":([LATIN],[SALSA],"Beginner"),
    "la gozadera":([LATIN],[SALSA],"Beginner"),
    "free style salsa":([LATIN],[SALSA],"Intermediate"),
    "hustle":([LATIN],[SALSA],"Intermediate"),
    "perico pincho pincho shaka shaka":([LATIN],[REGGAETON],"Beginner"),
    "borracho style":([LATIN],[REGGAETON],"Beginner"),
    "perico swag":([LATIN],[REGGAETON],"Beginner"),
    "salud":([LATIN],[SALSA],"Beginner"),
    "pa' lante":([LATIN],[SALSA],"Beginner"),
    "dile":([LATIN],[SALSA],"Beginner"),
    "pique":([LATIN],[SALSA],"Beginner"),
    "pika":([LATIN],[SALSA],"Beginner"),
    "g slide":([LATIN],[SALSA],"Beginner"),
    "b slide":([LATIN],[SALSA],"Beginner"),
    "4 count freeze":([LATIN],[SALSA],"Intermediate"),
    "c step":([LATIN],[SALSA],"Beginner"),
    "guapo":([LATIN],[SALSA],"Beginner"),
    "d step":([LATIN],[SALSA],"Beginner"),
    "pasa la olla":([LATIN],[SALSA],"Beginner"),
    "e step":([LATIN],[SALSA],"Beginner"),
    "la india":([LATIN],[SALSA],"Beginner"),
    "el taita":([LATIN],[SALSA],"Beginner"),
    "tumbando caja":([LATIN],[SALSA],"Beginner"),
    "g slide 2":([LATIN],[SALSA],"Beginner"),
    "pa' que te lo cuenten":([LATIN],[SALSA],"Beginner"),
    "b slide 2":([LATIN],[SALSA],"Beginner"),
    "c step 2":([LATIN],[SALSA],"Beginner"),
    "d step 2":([LATIN],[SALSA],"Beginner"),
    "e step 2":([LATIN],[SALSA],"Beginner"),
    "5 step":([LATIN],[SALSA],"Beginner"),
    "6 step 2":([LATIN],[SALSA],"Beginner"),
    "7 step":([LATIN],[SALSA],"Beginner"),
    "8 step":([LATIN],[SALSA],"Beginner"),
    "9 step":([LATIN],[SALSA],"Beginner"),
    "10 step":([LATIN],[SALSA],"Beginner"),
    "11 step":([LATIN],[SALSA],"Beginner"),
    "12 step":([LATIN],[SALSA],"Beginner"),
    "13 step":([LATIN],[SALSA],"Beginner"),
    "14 step":([LATIN],[SALSA],"Beginner"),
    "15 step":([LATIN],[SALSA],"Beginner"),
    "16 step":([LATIN],[SALSA],"Beginner"),
    "5 step 2":([LATIN],[SALSA],"Beginner"),
    "7 step 2":([LATIN],[SALSA],"Beginner"),
    "8 step 2":([LATIN],[SALSA],"Beginner"),
    "9 step 2":([LATIN],[SALSA],"Beginner"),
    "10 step 2":([LATIN],[SALSA],"Beginner"),
    "11 step 2":([LATIN],[SALSA],"Beginner"),
    "12 step 2":([LATIN],[SALSA],"Beginner"),
    "13 step 2":([LATIN],[SALSA],"Beginner"),
    "14 step 2":([LATIN],[SALSA],"Beginner"),
    "15 step 2":([LATIN],[SALSA],"Beginner"),
    "chupa":([LATIN],[SALSA],"Beginner"),
    "guantera":([LATIN],[SALSA],"Beginner"),
    "el caderito":([LATIN],[SALSA],"Beginner"),
    "salsa limpio":([LATIN],[SALSA],"Intermediate"),
    "salsero":([LATIN],[SALSA],"Intermediate"),
    "ojo que pasa":([LATIN],[SALSA],"Beginner"),
    "dile la verdad":([LATIN],[SALSA],"Beginner"),
    "vaina loca":([LATIN],[SALSA],"Beginner"),
    "rocío":([LATIN],[REGGAETON],"Beginner"),
    "la guagüita":([LATIN],[REGGAETON],"Beginner"),
    "la cucaracha":([LATIN],[SALSA],"Beginner"),
    "el puno":([LATIN],[REGGAETON],"Beginner"),
    "forward and backward ocho":([LATIN],[SALSA],"Intermediate"),
    "forward and backward giro":([LATIN],[SALSA],"Intermediate"),
    "forward and backward cross-body lead":([LATIN],[SALSA],"Intermediate"),
    "rápido":([LATIN],[SALSA],"Intermediate"),
    "gafas":([LATIN],[SALSA],"Beginner"),
    "lateral pass":([LATIN],[SALSA],"Intermediate"),
    "corta y vuelta":([LATIN],[SALSA],"Intermediate"),
    "palo de cuerpo":([LATIN],[SALSA],"Intermediate"),
    "sencillo":([LATIN],[SALSA],"Beginner"),
    "rondilla":([LATIN],[SALSA],"Intermediate"),
    "lazo":([LATIN],[SALSA],"Intermediate"),
    # ── Tango / Ballroom ───────────────────────────────────────────────────
    "tango":([BALLROOM],[TANGO],"Intermediate"),
    "waltz":([BALLROOM],[CLASSICAL],"Intermediate"),
    "foxtrot":([BALLROOM],[MJAZZ],"Intermediate"),
    "quickstep":([BALLROOM],[MJAZZ],"Advanced"),
    "viennese waltz":([BALLROOM],[CLASSICAL],"Advanced"),
    "natural turn":([BALLROOM],[MJAZZ],"Beginner"),
    "waltz rise and fall":([BALLROOM],[CLASSICAL],"Beginner"),
    "sway step":([BALLROOM],[MJAZZ],"Beginner"),
    "tango forward step":([BALLROOM],[TANGO],"Beginner"),
    "tango backward walk":([BALLROOM],[TANGO],"Beginner"),
    "tango forward walk":([BALLROOM],[TANGO],"Beginner"),
    "tango walks":([BALLROOM],[TANGO],"Beginner"),
    "tango pas de basque":([BALLROOM],[TANGO],"Intermediate"),
    "salida":([BALLROOM],[TANGO],"Intermediate"),
    "progressive link":([BALLROOM],[TANGO],"Beginner"),
    "closed promenade":([BALLROOM],[TANGO],"Beginner"),
    "promenade position":([BALLROOM],[TANGO],"Beginner"),
    "waltz jump":([BALLROOM],[CLASSICAL],"Intermediate"),
    "box step":([BALLROOM],[MJAZZ],"Beginner"),
    "underarm turn":([BALLROOM],[MJAZZ],"Beginner"),
    "overarm turn":([BALLROOM],[MJAZZ],"Beginner"),
    "pivot turn":([BALLROOM],[MJAZZ],"Beginner"),
    "forward lock":([BALLROOM],[MJAZZ],"Beginner"),
    "reverse lock":([BALLROOM],[MJAZZ],"Beginner"),
    "quick-quick-slow sequence":([BALLROOM],[MJAZZ],"Beginner"),
    "slow-slow-quick sequence":([BALLROOM],[MJAZZ],"Beginner"),
    "ronde de jambe (leg circle)":([BALLROOM],[MJAZZ],"Intermediate"),
    "chassé en avant (forward chassé)":([BALLROOM],[MJAZZ],"Beginner"),
    "chassé en arrière (backward chassé)":([BALLROOM],[MJAZZ],"Beginner"),
    "chassé en avant avec un pas derrière":([BALLROOM],[MJAZZ],"Intermediate"),
    "cross-step forward":([BALLROOM],[MJAZZ],"Beginner"),
    "cross-step backward":([BALLROOM],[MJAZZ],"Beginner"),
    "turn à gauche (left turn)":([BALLROOM],[MJAZZ],"Beginner"),
    "turn à droite (right turn)":([BALLROOM],[MJAZZ],"Beginner"),
    "east coast swing":([SWING],[MJAZZ],"Beginner"),
    "west coast swing":([SWING],[MJAZZ],"Intermediate"),
    # ── Swing ──────────────────────────────────────────────────────────────
    "lindy hop":([SWING],[MJAZZ],"Intermediate"),
    "jive":([SWING],[MJAZZ],"Intermediate"),
    "balboa":([SWING],[MJAZZ],"Advanced"),
    "charleston":([SWING],[MJAZZ],"Beginner"),
    "20s charleston":([SWING],[MJAZZ],"Beginner"),
    "jump charleston":([SWING],[MJAZZ],"Intermediate"),
    "shim sham":([SWING],[MJAZZ],"Intermediate"),
    "suzie q":([SWING],[MJAZZ],"Beginner"),
    "suzy q":([SWING],[MJAZZ],"Beginner"),
    "shorty george":([SWING],[MJAZZ],"Intermediate"),
    "lindy hopper":([SWING],[MJAZZ],"Intermediate"),
    "rockstep":([SWING],[MJAZZ],"Beginner"),
    "rock step":([SWING],[MJAZZ],"Beginner"),
    "tuck turn":([SWING],[MJAZZ],"Intermediate"),
    "swingout":([SWING],[MJAZZ],"Intermediate"),
    "boogie forward / back":([SWING],[MJAZZ],"Beginner"),
    "boogie drop":([SWING],[MJAZZ],"Beginner"),
    "bee's knees":([SWING],[MJAZZ],"Beginner"),
    "breeze knees":([SWING],[MJAZZ],"Beginner"),
    "cow tail":([SWING],[MJAZZ],"Beginner"),
    "cross over":([SWING],[MJAZZ],"Beginner"),
    "the chase":([SWING],[MJAZZ],"Intermediate"),
    "fishtail":([SWING],[MJAZZ],"Intermediate"),
    "grapevine":([SWING],[MJAZZ],"Beginner"),
    "groove walk":([SWING],[MJAZZ],"Beginner"),
    "half break":([SWING],[MJAZZ],"Intermediate"),
    "jig walk":([SWING],[MJAZZ],"Beginner"),
    "lock turn":([SWING],[MJAZZ],"Intermediate"),
    "opposites":([SWING],[MJAZZ],"Beginner"),
    "stomps":([SWING],[MJAZZ],"Beginner"),
    "skating":([SWING],[MJAZZ],"Intermediate"),
    "sidestep":([SWING],[MJAZZ],"Beginner"),
    "sink & grind":([SWING],[MJAZZ],"Intermediate"),
    "rise & grind":([SWING],[MJAZZ],"Intermediate"),
    "light jig step":([SWING],[MJAZZ],"Beginner"),
    "boogie forward":([SWING],[MJAZZ],"Beginner"),
    "boogie step":([SWING],[MJAZZ],"Beginner"),
    "break (shim sham) aka 'toba break'":([SWING],[MJAZZ],"Intermediate"),
    "break (half break) aka 'tiger rag break'":([SWING],[MJAZZ],"Intermediate"),
    "break-a-leg":([SWING],[MJAZZ],"Intermediate"),
    "cakewalk / camelwalk (classic)":([SWING],[MJAZZ],"Beginner"),
    "cakewalk / camelwalk (modern)":([SWING],[MJAZZ],"Beginner"),
    "camelwalk (backward)":([SWING],[MJAZZ],"Beginner"),
    "charleston (1920s)":([SWING],[MJAZZ],"Beginner"),
    "charleston (jump)":([SWING],[MJAZZ],"Intermediate"),
    "charleston (kansas city)":([SWING],[MJAZZ],"Intermediate"),
    "charleston (squat)":([SWING],[MJAZZ],"Intermediate"),
    "cool breeze (1953) aka 'grapevine'":([SWING],[MJAZZ],"Beginner"),
    "cool breeze (1970s)":([SWING],[MJAZZ],"Beginner"),
    "crossovers":([SWING],[MJAZZ],"Beginner"),
    "eagle slide":([SWING],[MJAZZ],"Intermediate"),
    "fall off the log":([SWING],[MJAZZ],"Intermediate"),
    "fall off the log (turning)":([SWING],[MJAZZ],"Intermediate"),
    "fishtails":([SWING],[MJAZZ],"Intermediate"),
    "grinds":([SWING],[MJAZZ],"Intermediate"),
    "hallelujahs aka 'shouts'":([SWING],[MJAZZ],"Beginner"),
    "heels (digs)":([SWING],[MJAZZ],"Beginner"),
    "heels (russian wing)":([SWING],[MJAZZ],"Advanced"),
    "hitchhiker":([SWING],[MJAZZ],"Beginner"),
    "itches":([SWING],[MJAZZ],"Beginner"),
    "jig walks":([SWING],[MJAZZ],"Beginner"),
    "knee slaps":([SWING],[MJAZZ],"Beginner"),
    "lowdown":([SWING],[MJAZZ],"Intermediate"),
    "mess around":([SWING],[MJAZZ],"Beginner"),
    "mooch aka 'four corners'":([SWING],[MJAZZ],"Beginner"),
    "opposites aka 'push n pull'":([SWING],[MJAZZ],"Beginner"),
    "paddle turn":([SWING],[MJAZZ],"Intermediate"),
    "pecks":([SWING],[MJAZZ],"Beginner"),
    "pecks (jackson 5)":([SWING],[MJAZZ],"Beginner"),
    "ride the pony":([SWING],[MJAZZ],"Beginner"),
    "rocks":([SWING],[MJAZZ],"Beginner"),
    "rusty dusty":([SWING],[MJAZZ],"Beginner"),
    "sailor kicks":([SWING],[MJAZZ],"Beginner"),
    "savoy kicks":([SWING],[MJAZZ],"Intermediate"),
    "scarecrow":([SWING],[MJAZZ],"Beginner"),
    "scissor kicks":([SWING],[MJAZZ],"Intermediate"),
    "shish-ka-boom-ba":([SWING],[MJAZZ],"Beginner"),
    "shoe shine":([SWING],[MJAZZ],"Beginner"),
    "skip up":([SWING],[MJAZZ],"Beginner"),
    "slip slops":([SWING],[MJAZZ],"Beginner"),
    "spank the baby":([SWING],[MJAZZ],"Beginner"),
    "stomp off":([SWING],[MJAZZ],"Beginner"),
    "struttin'":([SWING],[MJAZZ],"Beginner"),
    "tabby the cat":([SWING],[MJAZZ],"Beginner"),
    "tacky annie":([SWING],[MJAZZ],"Beginner"),
    "tick tocks":([SWING],[MJAZZ],"Beginner"),
    "truckin'":([SWING],[MJAZZ],"Beginner"),
    "turkey trots":([SWING],[MJAZZ],"Beginner"),
    "the breakaway":([SWING],[MJAZZ],"Intermediate"),
    "the camel walk":([SWING],[MJAZZ],"Beginner"),
    "swivels":([SWING],[MJAZZ],"Beginner"),
    "outside swivels":([SWING],[MJAZZ],"Beginner"),
    "inside swivels":([SWING],[MJAZZ],"Beginner"),
    "flicks":([SWING],[MJAZZ],"Intermediate"),
    "triple step":([SWING],[MJAZZ],"Beginner"),
    "toba-break (full break)":([SWING],[MJAZZ],"Intermediate"),
    "boogie forward (clap behind)":([SWING],[MJAZZ],"Beginner"),
    "boogie back aka 'back it up'":([SWING],[MJAZZ],"Beginner"),
    "box step (original)":([SWING],[MJAZZ],"Beginner"),
    "box step (contemporary)":([SWING],[MJAZZ],"Beginner"),
    "the breakaway":([SWING],[MJAZZ],"Intermediate"),
    "connection":([SWING],[MJAZZ],"None"),
    "promenade":([SWING],[MJAZZ],"Beginner"),
    "fifth position frame":([SWING],[MJAZZ],"Beginner"),
    "quick-quick-slow":([SWING],[MJAZZ],"Beginner"),
    "forward triple step":([SWING],[MJAZZ],"Beginner"),
    "backward triple step":([SWING],[MJAZZ],"Beginner"),
    "forward cross over":([SWING],[MJAZZ],"Beginner"),
    "backward cross over":([SWING],[MJAZZ],"Beginner"),
    "forward shuffle":([SWING],[MJAZZ],"Beginner"),
    "backward shuffle":([SWING],[MJAZZ],"Beginner"),
    "forward knee slide":([SWING],[MJAZZ],"Intermediate"),
    "backward knee slide":([SWING],[MJAZZ],"Intermediate"),
    "forward slide step":([SWING],[MJAZZ],"Beginner"),
    "backward slide step":([SWING],[MJAZZ],"Beginner"),
    "forward trotting step":([SWING],[MJAZZ],"Beginner"),
    "backward trotting step":([SWING],[MJAZZ],"Beginner"),
    "forward stomp":([SWING],[MJAZZ],"Beginner"),
    "backward stomp":([SWING],[MJAZZ],"Beginner"),
    "forward tuck turn":([SWING],[MJAZZ],"Intermediate"),
    "backward tuck turn":([SWING],[MJAZZ],"Intermediate"),
    "forward whip":([SWING],[MJAZZ],"Intermediate"),
    "backward whip":([SWING],[MJAZZ],"Intermediate"),
    "forward dip":([SWING],[MJAZZ],"Intermediate"),
    "backward dip":([SWING],[MJAZZ],"Intermediate"),
    "clockwise spin":([SWING],[MJAZZ],"Intermediate"),
    "counterclockwise spin":([SWING],[MJAZZ],"Intermediate"),
    "rotating basic":([SWING],[MJAZZ],"Beginner"),
    "throw out":([SWING],[MJAZZ],"Beginner"),
    "outside turn":([SWING],[MJAZZ],"Beginner"),
    "inside turn":([SWING],[MJAZZ],"Beginner"),
    "apple jack":([SWING],[MJAZZ],"Beginner"),
    "black bottom":([SWING],[MJAZZ],"Beginner"),
    "boogie forward (clap behind)":([SWING],[MJAZZ],"Beginner"),
    "wrap":([SWING],[MJAZZ],"Intermediate"),
    "dishrag out":([SWING],[MJAZZ],"Intermediate"),
    "handshake turn":([SWING],[MJAZZ],"Intermediate"),
    "open style spin":([SWING],[MJAZZ],"Intermediate"),
    "gentleman's turn":([SWING],[MJAZZ],"Intermediate"),
    "ladies' turn":([SWING],[MJAZZ],"Intermediate"),
    "spin bump":([SWING],[MJAZZ],"Intermediate"),
    "side bump":([SWING],[MJAZZ],"Beginner"),
    "single time vs. jive vs ecs":([SWING],[MJAZZ],"None"),
    "basic":([SWING],[MJAZZ],"Beginner"),
    "turning basic":([SWING],[MJAZZ],"Intermediate"),
    "under arm turn":([SWING],[MJAZZ],"Beginner"),
    "leader break through":([SWING],[MJAZZ],"Intermediate"),
    "shoulder check":([SWING],[MJAZZ],"Beginner"),
    # ── Waacking ───────────────────────────────────────────────────────────
    "waack choreo 1":([WAACKING],[MHIPHOP],"Intermediate"),
    "drape":([WAACKING],[MHIPHOP],"Intermediate"),
    "neck roll":([WAACKING],[MHIPHOP],"Beginner"),
    "catwalk & walk in the park":([WAACKING],[MHIPHOP],"Intermediate"),
    "waacking arm":([WAACKING],[MHIPHOP],"Beginner"),
    "arm roll":([WAACKING],[MHIPHOP],"Beginner"),
    "quick arms":([WAACKING],[MHIPHOP],"Intermediate"),
    "vogue dip":([VOGUE],[MHIPHOP],"Intermediate"),
    # ── Tap ────────────────────────────────────────────────────────────────
    "shuffle":([TAP],[MJAZZ],"Beginner"),
    "flap":([TAP],[MJAZZ],"Beginner"),
    "flap heel":([TAP],[MJAZZ],"Beginner"),
    "time step":([TAP],[MJAZZ],"Intermediate"),
    "double time step":([TAP],[MJAZZ],"Intermediate"),
    "triple time step":([TAP],[MJAZZ],"Intermediate"),
    "ball change":([TAP],[MJAZZ],"Beginner"),
    "brush step":([TAP],[MJAZZ],"Beginner"),
    "toe taps":([TAP],[MJAZZ],"Beginner"),
    "brush and drags":([TAP],[MJAZZ],"Beginner"),
    "toes":([TAP],[MJAZZ],"Beginner"),
    "heel clicks":([TAP],[MJAZZ],"Beginner"),
    "stomps & stamps":([TAP],[MJAZZ],"Beginner"),
    "normal shuffle":([TAP],[MJAZZ],"Beginner"),
    "shuffle + step":([TAP],[MJAZZ],"Beginner"),
    "shuffle + ball change":([TAP],[MJAZZ],"Beginner"),
    "hop + shuffle + step":([TAP],[MJAZZ],"Intermediate"),
    "hop + shuffle + step + shuffle + ball change":([TAP],[MJAZZ],"Intermediate"),
    "normal shuffle(fast)":([TAP],[MJAZZ],"Intermediate"),
    "shuffle + step(fast)":([TAP],[MJAZZ],"Intermediate"),
    "shuffle + ball change(fast)":([TAP],[MJAZZ],"Intermediate"),
    "hop + shuffle + step(fast)":([TAP],[MJAZZ],"Advanced"),
    "hop + shuffle + step + shuffle + ball change(fast)":([TAP],[MJAZZ],"Advanced"),
    "shuffle and flap":([TAP],[MJAZZ],"Beginner"),
    "brush kicks":([TAP],[MJAZZ],"Beginner"),
    "toe heels":([TAP],[MJAZZ],"Beginner"),
    "tap steps":([TAP],[MJAZZ],"Beginner"),
    "tap steps in place":([TAP],[MJAZZ],"Beginner"),
    "playing with rhythm":([TAP],[MJAZZ],"Intermediate"),
    "sweeps and fades":([TAP],[MJAZZ],"Intermediate"),
    "playing with hesitation":([TAP],[MJAZZ],"Intermediate"),
    "tuck turn styling":([TAP],[MJAZZ],"Intermediate"),
    "follow styling pump the brakes":([TAP],[MJAZZ],"Intermediate"),
    "mirroring":([TAP],[MJAZZ],"Intermediate"),
    # ── Flamenco ───────────────────────────────────────────────────────────
    "flamenco":([FLAMENCO],[MFLAMENCO],"Intermediate"),
    "zapateado":([FLAMENCO],[MFLAMENCO],"Intermediate"),
    "marcaje":([FLAMENCO],[MFLAMENCO],"Intermediate"),
    "llamada":([FLAMENCO],[MFLAMENCO],"Intermediate"),
    "remate":([FLAMENCO],[MFLAMENCO],"Intermediate"),
    "palmas":([FLAMENCO],[MFLAMENCO],"Beginner"),
    "paso de bulerías":([FLAMENCO],[MFLAMENCO],"Advanced"),
    # ── Afrobeats ──────────────────────────────────────────────────────────
    "zanku":([AFROBEATS],[MAFRO],"Beginner"),
    "shaku shaku":([AFROBEATS],[MAFRO],"Beginner"),
    "gbe body":([AFROBEATS],[MAFRO],"Beginner"),
    "kokomma":([AFROBEATS],[MAFRO],"Beginner"),
    "sukuma sukuma":([AFROBEATS],[MAFRO],"Beginner"),
    "aja move":([AFROBEATS],[MAFRO],"Beginner"),
    "shoki":([AFROBEATS],[MAFRO],"Beginner"),
    "dudupe":([AFROBEATS],[MAFRO],"Beginner"),
    "wankele":([AFROBEATS],[MAFRO],"Beginner"),
    "wawo dance":([AFROBEATS],[MAFRO],"Beginner"),
    "odunsi dance":([AFROBEATS],[MAFRO],"Beginner"),
    "mumu rara":([AFROBEATS],[MAFRO],"Beginner"),
    "oyi":([AFROBEATS],[MAFRO],"Beginner"),
    "gbe gbe":([AFROBEATS],[MAFRO],"Beginner"),
    "aiyelese o":([AFROBEATS],[MAFRO],"Beginner"),
    "ololufe":([AFROBEATS],[MAFRO],"Beginner"),
    "loko loko":([AFROBEATS],[MAFRO],"Beginner"),
    "sisi e":([AFROBEATS],[MAFRO],"Beginner"),
    "mazito":([AFROBEATS],[MAFRO],"Beginner"),
    "ikawe":([AFROBEATS],[MAFRO],"Beginner"),
    "eje aje":([AFROBEATS],[MAFRO],"Beginner"),
    "eje eje":([AFROBEATS],[MAFRO],"Beginner"),
    "dance for me":([AFROBEATS],[MAFRO],"Beginner"),
    "baba sowo":([AFROBEATS],[MAFRO],"Beginner"),
    "igboro igboro":([AFROBEATS],[MAFRO],"Beginner"),
    "dance like me":([AFROBEATS],[MAFRO],"Beginner"),
    "totori dance":([AFROBEATS],[MAFRO],"Beginner"),
    "tinukwai":([AFROBEATS],[MAFRO],"Beginner"),
    "femi fadana":([AFROBEATS],[MAFRO],"Beginner"),
    "baba ti owo":([AFROBEATS],[MAFRO],"Beginner"),
    "cultural dance":([AFROBEATS],[MAFRO],"Beginner"),
    "hip bop":([AFROBEATS],[MAFRO],"Beginner"),
    "apple jack":([AFROBEATS],[MAFRO],"Beginner"),
    "black bottom":([AFROBEATS],[MAFRO],"Beginner"),
    # ── Dancehall ──────────────────────────────────────────────────────────
    "pepper seed":([DANCEHALL],[MDANCEHALL],"Beginner"),
    "dutty rock":([DANCEHALL],[MDANCEHALL],"Beginner"),
    "wuk up":([DANCEHALL],[MDANCEHALL],"Beginner"),
    "gully side step":([DANCEHALL],[MDANCEHALL],"Beginner"),
    "choppa style":([DANCEHALL],[MDANCEHALL],"Beginner"),
    "killer bee":([DANCEHALL],[MDANCEHALL],"Beginner"),
    "palm tree walk":([DANCEHALL],[MDANCEHALL],"Beginner"),
    "festival stance":([DANCEHALL],[MDANCEHALL],"Beginner"),
    "gaze afar":([DANCEHALL],[MDANCEHALL],"Beginner"),
    "forward bicep bounce":([DANCEHALL],[MDANCEHALL],"Beginner"),
    "buss a bubble":([DANCEHALL],[MDANCEHALL],"Beginner"),
    "wiggle wiggle":([DANCEHALL],[MDANCEHALL],"Beginner"),
    "hill top jump":([DANCEHALL],[MDANCEHALL],"Beginner"),
    "cool breeze":([DANCEHALL],[MDANCEHALL],"Beginner"),
    # ── Contemporary ───────────────────────────────────────────────────────
    "contemporary":([CONTEMPORARY],[CLASSICAL],"Intermediate"),
    "floor work":([CONTEMPORARY],[CLASSICAL],"Intermediate"),
    "crawling movement":([CONTEMPORARY],[CLASSICAL],"Beginner"),
    "floor Work":([CONTEMPORARY],[CLASSICAL],"Intermediate"),
}

# ── Pattern rules (applied if exact match misses) ─────────────────────────
# Each: (regex, styles, music_ids, difficulty)
PATTERNS = [
    # Ballet French terms
    (r'\b(pli[ée]|tendu|arabesque|pirouette|fouett[ée]|jet[ée]|grand battement|'
     r'battement|relevé|releve|assemble|assembl[ée]|glissade|soutenu|pas de chat|'
     r'tour en l|couru|échappe|echappe|développ[ée]|developpe|pointe|fondu|frapp[ée]|'
     r'frapp[ée]|adagio|adage|bourrée|bourree|changement|entrechat|cabriole|'
     r'rond de jambe|ronde de jambe|ronds de jambe|pas de bourrée|pas de bourree|'
     r'degag[ée]|dégag[ée]|port de bras|attitude|sauté|saute|coupe|coupé|'
     r'tournant|sous sous|écarté|ecarte|pirouette|petite allegro)\b',
     [BALLET], [CLASSICAL], "Intermediate"),
    # Flamenco terms
    (r'\b(flamenco|zapateado|marcaje|llamada|remate|palmas|compás|bulerías|buler|letra|remate)\b',
     [FLAMENCO], [MFLAMENCO], "Intermediate"),
    # Swing / Lindy
    (r'\b(lindy|charleston|shim sham|suzy q|savoy|jig walk|truckin|sailor kick|'
     r'tacky annie|shorty george|boogie woogie|rockstep|swing out|swingout)\b',
     [SWING], [MJAZZ], "Intermediate"),
    # Breakdance power/freeze
    (r'\b(freeze|flare|windmill|headspin|power move|b-boy|bboy|toprock|'
     r'footwork|airchair|airfreeze|backspin|handstand|headstand|kip.?up|'
     r'jackhammer|elbow.?freeze|shoulder.?freeze|neck.?freeze)\b',
     [BREAKDANCE], [MHIPHOP], "Intermediate"),
    # Tap
    (r'\b(time step|shuffle.and.flap|heel.dig|toe.tap|stamp.stomp|'
     r'cramp.?roll|riff|pick.?up)\b',
     [TAP], [MJAZZ], "Intermediate"),
    # Hip-hop general
    (r'\b(hip.?hop|hiphop|krump|twerk|dab|nae nae|whip|stanky|dougie|'
     r'cabbage|running man|roger rabbit)\b',
     [HIPHOP], [MHIPHOP], "Beginner"),
    # Afrobeats
    (r'\b(afrobeats|afro|azonto|skelewu|shoki|zanku|gbese|yahooze|'
     r'kukere|alanta|gwara gwara)\b',
     [AFROBEATS], [MAFRO], "Beginner"),
    # Dancehall
    (r'\b(dancehall|riddim|dutty|daggering|bogle|wuk up|passa passa)\b',
     [DANCEHALL], [MDANCEHALL], "Beginner"),
    # Latin
    (r'\b(salsa|bachata|merengue|cumbia|reggaeton|cha.?cha|mambo|rumba|'
     r'paso doble|bolero|samba|latin)\b',
     [LATIN], [SALSA], "Intermediate"),
    # K-pop
    (r'\b(k.?pop|kpop|bts|blackpink|twice|idol)\b',
     [KPOP], [JPOP], "Intermediate"),
]

def classify(name):
    n = name.lower().strip()
    if n in EXACT:
        return EXACT[n]
    for pat, styles, music, diff in PATTERNS:
        if re.search(pat, n, re.IGNORECASE):
            return (styles, music, diff)
    return None  # no match — keep existing

def main():
    print("Logging in...")
    token = login()

    print("Fetching dances...")
    dances, _ = api("GET", "/dances", token=token)
    print(f"Total: {len(dances)}")

    # Load progress if exists
    try:
        with open("claude_classify_progress.json") as f:
            done = set(json.load(f))
        print(f"Resuming — {len(done)} already done")
    except FileNotFoundError:
        done = set()

    updated = skipped = no_match = 0

    for i, dance in enumerate(dances):
        did = dance["id"]
        dname = dance["name"]

        if did in done:
            continue

        result = classify(dname)
        if result is None:
            no_match += 1
            done.add(did)
            continue

        style_ids, music_ids, difficulty = result
        body = {"styleIds": style_ids, "musicalStyleIds": music_ids, "difficulty": difficulty}

        resp, code = api("PUT", f"/dances/{did}", body, token)
        if code in (200, 204):
            print(f"[{i+1}] OK  {dname} -> styles={style_ids} music={music_ids} {difficulty}")
            updated += 1
        elif code == 404:
            print(f"[{i+1}] 404 {dname}")
        else:
            print(f"[{i+1}] ERR {code} {dname}")
            skipped += 1

        done.add(did)
        if len(done) % 50 == 0:
            with open("claude_classify_progress.json", "w") as f:
                json.dump(list(done), f)
        time.sleep(0.05)

    with open("claude_classify_progress.json", "w") as f:
        json.dump(list(done), f)

    print(f"\nDone — updated={updated}, no_match(kept existing)={no_match}, errors={skipped}")

if __name__ == "__main__":
    main()
