// <auto-generated />
using System;
using DancePlatform.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DancePlatform.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223235423_AddMusicalStyles")]
    partial class AddMusicalStyles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DancePlatform.API.Models.Dance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dances");
                });

            modelBuilder.Entity("DancePlatform.API.Models.DanceMusicalStyle", b =>
                {
                    b.Property<int>("DanceId")
                        .HasColumnType("integer");

                    b.Property<int>("MusicalStyleId")
                        .HasColumnType("integer");

                    b.HasKey("DanceId", "MusicalStyleId");

                    b.HasIndex("MusicalStyleId");

                    b.ToTable("DanceMusicalStyles");
                });

            modelBuilder.Entity("DancePlatform.API.Models.DanceStyle", b =>
                {
                    b.Property<int>("DanceId")
                        .HasColumnType("integer");

                    b.Property<int>("StyleId")
                        .HasColumnType("integer");

                    b.HasKey("DanceId", "StyleId");

                    b.HasIndex("StyleId");

                    b.ToTable("DanceStyles");
                });

            modelBuilder.Entity("DancePlatform.API.Models.MusicalStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MusicalStyles");
                });

            modelBuilder.Entity("DancePlatform.API.Models.Style", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Styles");
                });

            modelBuilder.Entity("DancePlatform.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserFavoriteDance", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("DanceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "DanceId");

                    b.HasIndex("DanceId");

                    b.ToTable("UserFavoriteDances");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserLearnedDance", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("DanceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "DanceId");

                    b.HasIndex("DanceId");

                    b.ToTable("UserLearnedDances");
                });

            modelBuilder.Entity("DancePlatform.API.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DanceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YouTubeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DanceId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("DancePlatform.API.Models.DanceMusicalStyle", b =>
                {
                    b.HasOne("DancePlatform.API.Models.Dance", "Dance")
                        .WithMany("DanceMusicalStyles")
                        .HasForeignKey("DanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DancePlatform.API.Models.MusicalStyle", "MusicalStyle")
                        .WithMany("DanceMusicalStyles")
                        .HasForeignKey("MusicalStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dance");

                    b.Navigation("MusicalStyle");
                });

            modelBuilder.Entity("DancePlatform.API.Models.DanceStyle", b =>
                {
                    b.HasOne("DancePlatform.API.Models.Dance", "Dance")
                        .WithMany("DanceStyles")
                        .HasForeignKey("DanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DancePlatform.API.Models.Style", "Style")
                        .WithMany("DanceStyles")
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dance");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserFavoriteDance", b =>
                {
                    b.HasOne("DancePlatform.API.Models.Dance", "Dance")
                        .WithMany("FavoritedBy")
                        .HasForeignKey("DanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DancePlatform.API.Models.User", "User")
                        .WithMany("FavoriteDances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserLearnedDance", b =>
                {
                    b.HasOne("DancePlatform.API.Models.Dance", "Dance")
                        .WithMany("LearnedBy")
                        .HasForeignKey("DanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DancePlatform.API.Models.User", "User")
                        .WithMany("LearnedDances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DancePlatform.API.Models.Video", b =>
                {
                    b.HasOne("DancePlatform.API.Models.Dance", "Dance")
                        .WithMany("Videos")
                        .HasForeignKey("DanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dance");
                });

            modelBuilder.Entity("DancePlatform.API.Models.Dance", b =>
                {
                    b.Navigation("DanceMusicalStyles");

                    b.Navigation("DanceStyles");

                    b.Navigation("FavoritedBy");

                    b.Navigation("LearnedBy");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("DancePlatform.API.Models.MusicalStyle", b =>
                {
                    b.Navigation("DanceMusicalStyles");
                });

            modelBuilder.Entity("DancePlatform.API.Models.Style", b =>
                {
                    b.Navigation("DanceStyles");
                });

            modelBuilder.Entity("DancePlatform.API.Models.User", b =>
                {
                    b.Navigation("FavoriteDances");

                    b.Navigation("LearnedDances");
                });
#pragma warning restore 612, 618
        }
    }
}
