// <auto-generated />
using System;
using DancePlatform.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DancePlatform.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903175524_AddDanceProvenanceAndReview")]
    partial class AddDanceProvenanceAndReview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DancePlatform.API.Models.Dance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("FavoriteCount")
                        .HasColumnType("integer");

                    b.Property<int>("LearnedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("integer");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ReviewState");

                    b.HasIndex("Slug");

                    b.ToTable("Dances");
                });

            modelBuilder.Entity("DancePlatform.API.Models.DanceInstructor", b =>
                {
                    b.Property<int>("DanceId")
                        .HasColumnType("integer");

                    b.Property<int>("InstructorId")
                        .HasColumnType("integer");

                    b.HasKey("DanceId", "InstructorId");

                    b.HasIndex("InstructorId");

                    b.ToTable("DanceInstructors");
                });

            modelBuilder.Entity("DancePlatform.API.Models.DanceMusicalStyle", b =>
                {
                    b.Property<int>("DanceId")
                        .HasColumnType("integer");

                    b.Property<int>("MusicalStyleId")
                        .HasColumnType("integer");

                    b.HasKey("DanceId", "MusicalStyleId");

                    b.HasIndex("MusicalStyleId");

                    b.ToTable("DanceMusicalStyles");
                });

            modelBuilder.Entity("DancePlatform.API.Models.DanceStyle", b =>
                {
                    b.Property<int>("DanceId")
                        .HasColumnType("integer");

                    b.Property<int>("StyleId")
                        .HasColumnType("integer");

                    b.HasKey("DanceId", "StyleId");

                    b.HasIndex("StyleId");

                    b.ToTable("DanceStyles");
                });

            modelBuilder.Entity("DancePlatform.API.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("DancePlatform.API.Models.MusicalStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MusicalStyles");
                });

            modelBuilder.Entity("DancePlatform.API.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("DancePlatform.API.Models.PracticeSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LastActivityAt");

                    b.ToTable("PracticeSessions");
                });

            modelBuilder.Entity("DancePlatform.API.Models.PracticeSessionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DanceId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PracticeSessionId")
                        .HasColumnType("integer");

                    b.Property<int>("Seconds")
                        .HasColumnType("integer");

                    b.Property<int?>("UserChoreoId")
                        .HasColumnType("integer");

                    b.Property<int?>("VideoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DanceId");

                    b.HasIndex("UserChoreoId");

                    b.HasIndex("VideoId");

                    b.HasIndex("PracticeSessionId", "DanceId");

                    b.ToTable("PracticeSessionItems");
                });

            modelBuilder.Entity("DancePlatform.API.Models.Roadmap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("StyleId")
                        .HasColumnType("integer");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("StyleId");

                    b.ToTable("Roadmaps");
                });

            modelBuilder.Entity("DancePlatform.API.Models.RoadmapStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("RoadmapId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapId");

                    b.ToTable("RoadmapStages");
                });

            modelBuilder.Entity("DancePlatform.API.Models.RoadmapStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChildRoadmapId")
                        .HasColumnType("integer");

                    b.Property<int?>("DanceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoadmapStageId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VideoSegmentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildRoadmapId")
                        .IsUnique()
                        .HasFilter("\"ChildRoadmapId\" IS NOT NULL");

                    b.HasIndex("DanceId");

                    b.HasIndex("RoadmapStageId");

                    b.HasIndex("VideoSegmentId");

                    b.ToTable("RoadmapSteps");
                });

            modelBuilder.Entity("DancePlatform.API.Models.RoadmapStepPrerequisite", b =>
                {
                    b.Property<int>("StepId")
                        .HasColumnType("integer");

                    b.Property<int>("PrerequisiteStepId")
                        .HasColumnType("integer");

                    b.HasKey("StepId", "PrerequisiteStepId");

                    b.HasIndex("PrerequisiteStepId");

                    b.ToTable("RoadmapStepPrerequisites");
                });

            modelBuilder.Entity("DancePlatform.API.Models.Style", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Styles");
                });

            modelBuilder.Entity("DancePlatform.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokensValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseBetaViewer")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserChoreo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RotationDegrees")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserChoreos");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserChoreoLoop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EndTime")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartTime")
                        .HasColumnType("integer");

                    b.Property<int>("UserChoreoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserChoreoId");

                    b.ToTable("UserChoreoLoops");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserFavoriteDance", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("DanceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "DanceId");

                    b.HasIndex("DanceId");

                    b.ToTable("UserFavoriteDances");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserInProgressDance", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("DanceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "DanceId");

                    b.HasIndex("DanceId");

                    b.ToTable("UserInProgressDances");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserLearnedDance", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("DanceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "DanceId");

                    b.HasIndex("DanceId");

                    b.ToTable("UserLearnedDances");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserMyStyle", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("StyleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "StyleId");

                    b.HasIndex("StyleId");

                    b.ToTable("UserMyStyles");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserVideoLoop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EndTime")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartTime")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("VideoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.HasIndex("UserId", "VideoId");

                    b.ToTable("UserVideoLoops");
                });

            modelBuilder.Entity("DancePlatform.API.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<int>("DanceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("EndTime")
                        .HasColumnType("integer");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QualityFlags")
                        .HasColumnType("text");

                    b.Property<float?>("QualityScore")
                        .HasColumnType("real");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<string>("ReviewState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("StartTime")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DanceId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ReviewState");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("DancePlatform.API.Models.VideoNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("VideoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.HasIndex("UserId", "VideoId");

                    b.ToTable("VideoNotes");
                });

            modelBuilder.Entity("DancePlatform.API.Models.VideoRating", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("VideoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "VideoId");

                    b.HasIndex("VideoId");

                    b.ToTable("VideoRatings");
                });

            modelBuilder.Entity("DancePlatform.API.Models.VideoSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("Confidence")
                        .HasColumnType("real");

                    b.Property<int?>("EndTime")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int>("StartTime")
                        .HasColumnType("integer");

                    b.Property<int>("VideoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("VideoSegments");
                });

            modelBuilder.Entity("DancePlatform.API.Models.Dance", b =>
                {
                    b.HasOne("DancePlatform.API.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DancePlatform.API.Models.DanceInstructor", b =>
                {
                    b.HasOne("DancePlatform.API.Models.Dance", "Dance")
                        .WithMany("DanceInstructors")
                        .HasForeignKey("DanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DancePlatform.API.Models.Instructor", "Instructor")
                        .WithMany("DanceInstructors")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dance");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("DancePlatform.API.Models.DanceMusicalStyle", b =>
                {
                    b.HasOne("DancePlatform.API.Models.Dance", "Dance")
                        .WithMany("DanceMusicalStyles")
                        .HasForeignKey("DanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DancePlatform.API.Models.MusicalStyle", "MusicalStyle")
                        .WithMany("DanceMusicalStyles")
                        .HasForeignKey("MusicalStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dance");

                    b.Navigation("MusicalStyle");
                });

            modelBuilder.Entity("DancePlatform.API.Models.DanceStyle", b =>
                {
                    b.HasOne("DancePlatform.API.Models.Dance", "Dance")
                        .WithMany("DanceStyles")
                        .HasForeignKey("DanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DancePlatform.API.Models.Style", "Style")
                        .WithMany("DanceStyles")
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dance");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("DancePlatform.API.Models.PasswordResetToken", b =>
                {
                    b.HasOne("DancePlatform.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DancePlatform.API.Models.PracticeSession", b =>
                {
                    b.HasOne("DancePlatform.API.Models.User", "User")
                        .WithMany("PracticeSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DancePlatform.API.Models.PracticeSessionItem", b =>
                {
                    b.HasOne("DancePlatform.API.Models.Dance", "Dance")
                        .WithMany("PracticeItems")
                        .HasForeignKey("DanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DancePlatform.API.Models.PracticeSession", "Session")
                        .WithMany("Items")
                        .HasForeignKey("PracticeSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DancePlatform.API.Models.UserChoreo", "Choreo")
                        .WithMany()
                        .HasForeignKey("UserChoreoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DancePlatform.API.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Choreo");

                    b.Navigation("Dance");

                    b.Navigation("Session");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("DancePlatform.API.Models.Roadmap", b =>
                {
                    b.HasOne("DancePlatform.API.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DancePlatform.API.Models.Style", "Style")
                        .WithMany()
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("DancePlatform.API.Models.RoadmapStage", b =>
                {
                    b.HasOne("DancePlatform.API.Models.Roadmap", "Roadmap")
                        .WithMany("Stages")
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("DancePlatform.API.Models.RoadmapStep", b =>
                {
                    b.HasOne("DancePlatform.API.Models.Roadmap", "ChildRoadmap")
                        .WithMany()
                        .HasForeignKey("ChildRoadmapId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DancePlatform.API.Models.Dance", "Dance")
                        .WithMany()
                        .HasForeignKey("DanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DancePlatform.API.Models.RoadmapStage", "Stage")
                        .WithMany("Steps")
                        .HasForeignKey("RoadmapStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DancePlatform.API.Models.VideoSegment", "VideoSegment")
                        .WithMany()
                        .HasForeignKey("VideoSegmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChildRoadmap");

                    b.Navigation("Dance");

                    b.Navigation("Stage");

                    b.Navigation("VideoSegment");
                });

            modelBuilder.Entity("DancePlatform.API.Models.RoadmapStepPrerequisite", b =>
                {
                    b.HasOne("DancePlatform.API.Models.RoadmapStep", "PrerequisiteStep")
                        .WithMany()
                        .HasForeignKey("PrerequisiteStepId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DancePlatform.API.Models.RoadmapStep", "Step")
                        .WithMany("Prerequisites")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrerequisiteStep");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserChoreo", b =>
                {
                    b.HasOne("DancePlatform.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserChoreoLoop", b =>
                {
                    b.HasOne("DancePlatform.API.Models.UserChoreo", "Choreo")
                        .WithMany("Loops")
                        .HasForeignKey("UserChoreoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Choreo");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserFavoriteDance", b =>
                {
                    b.HasOne("DancePlatform.API.Models.Dance", "Dance")
                        .WithMany("FavoritedBy")
                        .HasForeignKey("DanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DancePlatform.API.Models.User", "User")
                        .WithMany("FavoriteDances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserInProgressDance", b =>
                {
                    b.HasOne("DancePlatform.API.Models.Dance", "Dance")
                        .WithMany("InProgressBy")
                        .HasForeignKey("DanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DancePlatform.API.Models.User", "User")
                        .WithMany("InProgressDances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserLearnedDance", b =>
                {
                    b.HasOne("DancePlatform.API.Models.Dance", "Dance")
                        .WithMany("LearnedBy")
                        .HasForeignKey("DanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DancePlatform.API.Models.User", "User")
                        .WithMany("LearnedDances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserLogin", b =>
                {
                    b.HasOne("DancePlatform.API.Models.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserMyStyle", b =>
                {
                    b.HasOne("DancePlatform.API.Models.Style", "Style")
                        .WithMany("MyStyleUsers")
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DancePlatform.API.Models.User", "User")
                        .WithMany("MyStyles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Style");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserVideoLoop", b =>
                {
                    b.HasOne("DancePlatform.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DancePlatform.API.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("DancePlatform.API.Models.Video", b =>
                {
                    b.HasOne("DancePlatform.API.Models.Dance", "Dance")
                        .WithMany("Videos")
                        .HasForeignKey("DanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DancePlatform.API.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Dance");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DancePlatform.API.Models.VideoNote", b =>
                {
                    b.HasOne("DancePlatform.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DancePlatform.API.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("DancePlatform.API.Models.VideoRating", b =>
                {
                    b.HasOne("DancePlatform.API.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DancePlatform.API.Models.Video", "Video")
                        .WithMany("Ratings")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("DancePlatform.API.Models.VideoSegment", b =>
                {
                    b.HasOne("DancePlatform.API.Models.Video", "Video")
                        .WithMany("Segments")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("DancePlatform.API.Models.Dance", b =>
                {
                    b.Navigation("DanceInstructors");

                    b.Navigation("DanceMusicalStyles");

                    b.Navigation("DanceStyles");

                    b.Navigation("FavoritedBy");

                    b.Navigation("InProgressBy");

                    b.Navigation("LearnedBy");

                    b.Navigation("PracticeItems");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("DancePlatform.API.Models.Instructor", b =>
                {
                    b.Navigation("DanceInstructors");
                });

            modelBuilder.Entity("DancePlatform.API.Models.MusicalStyle", b =>
                {
                    b.Navigation("DanceMusicalStyles");
                });

            modelBuilder.Entity("DancePlatform.API.Models.PracticeSession", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DancePlatform.API.Models.Roadmap", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("DancePlatform.API.Models.RoadmapStage", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("DancePlatform.API.Models.RoadmapStep", b =>
                {
                    b.Navigation("Prerequisites");
                });

            modelBuilder.Entity("DancePlatform.API.Models.Style", b =>
                {
                    b.Navigation("DanceStyles");

                    b.Navigation("MyStyleUsers");
                });

            modelBuilder.Entity("DancePlatform.API.Models.User", b =>
                {
                    b.Navigation("FavoriteDances");

                    b.Navigation("InProgressDances");

                    b.Navigation("LearnedDances");

                    b.Navigation("Logins");

                    b.Navigation("MyStyles");

                    b.Navigation("PracticeSessions");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("DancePlatform.API.Models.UserChoreo", b =>
                {
                    b.Navigation("Loops");
                });

            modelBuilder.Entity("DancePlatform.API.Models.Video", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
